version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}

  app:
    container_name: app
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/app
    depends_on:
      - db
    links:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run dev
